### ISSUE TITLE
Game worker crashes when snake endpoint returns HTTP 400

### ISSUE THREAD

**Issue by robbles** [sendwithus/battlesnake-server#4]
Looks like this happens every time I've tested, and the game just stops working after that. The client seems to get stuck, so I'm not sure if the game recovers or not. The main server stays up and you can start a new game afterwards - you just can't continue the previous game.

Logs + stack trace (this is everything that's output after clicking the "Show" link on a game):

```
18:55:06.016 request_id=egf18qqi49ifimvsoimcivi4dfu4lgt8 [info] GET /1
18:55:06.017 request_id=egf18qqi49ifimvsoimcivi4dfu4lgt8 [info] Sent 200 in 829µs
18:55:06.128 [info] JOIN "game:1" to BsWeb.GameChannel
  Transport:  Phoenix.Transports.WebSocket (1.0.0)
  Serializer:  Phoenix.Transports.WebSocketSerializer
  Parameters: %{"id" => "1"}
18:55:06.128 [info] Replied game:1 :ok
18:55:06.134 [error] Task #PID<0.1730.0> started from #PID<0.1723.0> terminating
** (Poison.SyntaxError) Unexpected end of input at position 0
    (poison) lib/poison/parser.ex:55: Poison.Parser.parse!/2
    (poison) lib/poison.ex:83: Poison.decode!/2
    (bs) lib/bs/world/factory.ex:129: Bs.World.Factory.Worker.run/3
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: &Bs.World.Factory.Worker.run/3
    Args: [%BsWeb.SnakeForm{delete: nil, id: "7f662b1d-5b23-495c-b3e2-f97618eb4ee9", url: "http://10.53.236.72:9000"}, 1, "{\"width\":20,\"height\":20,\"game_id\":1}"]

=CRASH REPORT==== 7-Feb-2018::18:55:06 ===
  crasher:
    initial call: Elixir.Bs.World.Factory.Worker:run/3
    pid: <0.1730.0>
    registered_name: []
    exception exit: {#{'__exception__' => true,
                       '__struct__' => 'Elixir.Poison.SyntaxError',
                       message => <<"Unexpected end of input at position 0">>,
                       pos => nil,token => nil},
                     [{'Elixir.Poison.Parser','parse!',2,
                          [{file,"lib/poison/parser.ex"},{line,55}]},
                      {'Elixir.Poison','decode!',2,
                          [{file,"lib/poison.ex"},{line,83}]},
                      {'Elixir.Bs.World.Factory.Worker',run,3,
                          [{file,"lib/bs/world/factory.ex"},{line,129}]},
                      {'Elixir.Task.Supervised',do_apply,2,
                          [{file,"lib/task/supervised.ex"},{line,88}]},
                      {'Elixir.Task.Supervised',reply,5,
                          [{file,"lib/task/supervised.ex"},{line,38}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,247}]}]}
      in function  'Elixir.Task.Supervised':exit/4 (lib/task/supervised.ex, line 121)
      in call from 'Elixir.Task.Supervised':reply/5 (lib/task/supervised.ex, line 38)
    ancestors: [<0.1728.0>,<0.1723.0>,'Elixir.Bs.Game.Supervisor',
                  'Elixir.Bs.Supervisor',<0.1558.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1728.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 4634
  neighbours:
```

**Comment by daniel-swu** [comment]
Thanks Rob for the report, we'll investigate and fix this issue.

**Comment by dlsteuer** [comment]
So the problem here wasn't that the snake server returned a 400, but the fact that the response body was empty, this caused the Poison json parser to bail. So fixing json parsing to handle errors fixes this issue.
